# Generated by Django 4.0.4 on 2022-06-25 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaAgir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conceitosSolucao', models.TextField(default='Não concluído.', help_text='Podem envolver planos para uma campanha para informar ou educar, projetos de melhoria da escola ou da Comunidade, desenvolvimento de produtos ou outras atividades.', verbose_name='Conceitos de Solução')),
                ('implementacaoSolucao', models.FileField(help_text='Após a aprovação do conceito de solução, os aprendizes desenvolvem protótipos, experimentos e testes.', null=True, upload_to='uploads/', verbose_name='Implementação da Solução')),
                ('avaliacao', models.TextField(default='Não concluído.', help_text='Hora de medir os resultados, refletir sobre o que funcionou e o que não e determinar o seu impacto sobre o desafio.', verbose_name='Avaliação final')),
                ('documentos', models.FileField(help_text='Adicione aqui arquivos de materiais que considerar agregadores ao desafio.', null=True, upload_to='uploads/', verbose_name='Materiais Auxiliadores')),
            ],
            options={
                'verbose_name': 'Etapa Agir',
                'verbose_name_plural': 'Etapas Agir',
            },
        ),
        migrations.CreateModel(
            name='EtapaEnvolver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grandeIdeia', models.TextField(default='Não concluído.', help_text='Exemplos de grandes ideias incluem Comunidade, Empoderamento Social, Criatividade, Saúde, Sustentabilidade e Democracia.', verbose_name='A Grande Ideia (Tema)')),
                ('questaoEssencial', models.TextField(default='Não concluído.', help_text='Por exemplo: O que preciso fazer para ser mais saudável?', verbose_name='Questão Essencial (Pergunta)')),
                ('desafios', models.TextField(default='Não concluído.', help_text='É a solução para a questão levantada, deve ser imediata e possível de realizar.', verbose_name='O Desafio (Solução)')),
                ('documentos', models.FileField(help_text='Adicione aqui arquivos de materiais que considerar agregadores ao desafio.', null=True, upload_to='uploads/', verbose_name='Materiais Auxiliadores')),
            ],
            options={
                'verbose_name': 'Etapa Envolver',
                'verbose_name_plural': 'Etapas Envolver',
            },
        ),
        migrations.CreateModel(
            name='EtapaInvestigar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questoesNorteadoras', models.TextField(default='Não concluído.', help_text='Questões relacionadas com o desafio, é importante fazer variadas perguntas sobre o tema definido.', verbose_name='Questões Norteadoras (Perguntas guias)')),
                ('recursos', models.TextField(default='Não concluído.', help_text='Exemplos de recursos orientadores incluem: conteúdo online e cursos, bancos de dados, livros didáticos e redes sociais.', verbose_name='Recursos orientadores')),
                ('atividades', models.TextField(default='Não concluído.', help_text='Exemplos de atividades orientadoras incluem: simulações, experimentos, projetos, conjuntos de problemas, pesquisa e jogos.', verbose_name='Atividades orientadoras')),
                ('sintese', models.TextField(default='Não concluído.', help_text='A análise das lições aprendidas durante as questões guias, recursos e atividades.', verbose_name='Síntese avaliadora')),
                ('documentos', models.FileField(help_text='Adicione aqui arquivos de materiais que considerar agregadores ao desafio.', null=True, upload_to='uploads/', verbose_name='Materiais Auxiliadores')),
            ],
            options={
                'verbose_name': 'Etapa Investigar',
                'verbose_name_plural': 'Etapas Investigar',
            },
        ),
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('dataCriacao', models.DateTimeField(auto_now=True, verbose_name='Data de criação')),
                ('etapaAgir', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cbl_app.etapaagir')),
                ('etapaEnvolver', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cbl_app.etapaenvolver')),
                ('etapaInvestigar', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cbl_app.etapainvestigar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='desafios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Desafio',
                'verbose_name_plural': 'Desafios',
                'ordering': ['dataCriacao'],
            },
        ),
    ]
