# Generated by Django 4.0.4 on 2022-06-25 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbl_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafio',
            name='etapaAgir',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='cbl_app.etapaagir'),
        ),
        migrations.AlterField(
            model_name='desafio',
            name='etapaEnvolver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='cbl_app.etapaenvolver'),
        ),
        migrations.AlterField(
            model_name='desafio',
            name='etapaInvestigar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='cbl_app.etapainvestigar'),
        ),
        migrations.AlterField(
            model_name='etapaagir',
            name='documentos',
            field=models.FileField(blank=True, help_text='Adicione aqui arquivos de materiais que considerar agregadores ao desafio.', upload_to='uploads/', verbose_name='Materiais Auxiliadores'),
        ),
        migrations.AlterField(
            model_name='etapaagir',
            name='implementacaoSolucao',
            field=models.FileField(blank=True, help_text='Após a aprovação do conceito de solução, os aprendizes desenvolvem protótipos, experimentos e testes.', upload_to='uploads/', verbose_name='Implementação da Solução'),
        ),
        migrations.AlterField(
            model_name='etapaenvolver',
            name='documentos',
            field=models.FileField(blank=True, help_text='Adicione aqui arquivos de materiais que considerar agregadores ao desafio.', upload_to='uploads/', verbose_name='Materiais Auxiliadores'),
        ),
        migrations.AlterField(
            model_name='etapainvestigar',
            name='documentos',
            field=models.FileField(blank=True, help_text='Adicione aqui arquivos de materiais que considerar agregadores ao desafio.', upload_to='uploads/', verbose_name='Materiais Auxiliadores'),
        ),
    ]
